[package]
name = "lambda_runtime_types"
version = "0.1.0"
authors = ["Marc Mettke <marc@itmettke.de>"]
edition = "2018"
description = "Common structures for lambda architecture"
license = "MIT OR Apache-2.0"
repository = "https://github.com/mettke/lambda_runtime_types"
readme = "./README.md"
keywords = ["lambda", "types"]
categories = ["data-structures"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
rotate = ["rusoto_core", "rusoto_secretsmanager", "serde_json"]
test = ["serde_json"]

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
futures = "0.3"
lambda_runtime = "0.4"
log = "0.4"
rusoto_core = { version = "0.47", optional = true }
rusoto_secretsmanager = { version = "0.47", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", optional = true }
tokio = { version = "1.10" }

[dev-dependencies]
simple_logger = "1.13"
serde_json = "1.0"
